### ISSUE TITLE
No response form the API

### ISSUE THREAD

**Issue by agrawal-mohit** [hiroakis/tornado-websocket-example#3]
I tried : curl "http://hiroakis.com:8888/api?id=1&value=100" 
at the command prompt. 

I didn't get any response on the terminal nor the browser displayed any change.

How can I see it live ?

**Comment by hiroakis** [comment]
@agrawal-mohit I confirm whether the server is live or not just now. The server is alive. could you re-check ?

**Comment by agrawal-mohit** [comment]
I'm sorry I just checked, it's not up.

**Comment by hiroakis** [comment]
@agrawal-mohit 
could you check as following?

1. visit demo site( http://hiroakis.com:8888/ ) with your browser.
2. execute curl command `curl "http://hiroakis.com:8888/api?id=1&value=100"`

If value of table "id 1" becomes "100" on browser, the tool works well.

Do you expect to receive http response body?
I'm sorry the api doesn't return any http body. It just pushes data to websocket client.

**Comment by agrawal-mohit** [comment]
I didn't expect to receive http response body but just that the value changes on the browser. And it seems to be working now. Thanks!

**Comment by hiroakis** [comment]
@agrawal-mohit 
You're welcome. I'll close the issue. Thx!
