### ISSUE TITLE
Can "Upgrade" only to "WebSocket".

### ISSUE THREAD

**Issue by shafayeatsumit** [hiroakis/tornado-websocket-example#7]
I am getting this error while hitting this url. what's the solution
http://hiroakis.com:8888/ws

**Comment by hiroakis** [comment]
@shafayeatsumit Thank you for your comment. Please visit http://hiroakis.com:8888. It works.

**Comment by guaiqueri69** [comment]
Iam sorry http://hiroakis.com:8888/ is good :) http://hiroakis.com:8888/api?id=1&value=100 is bad u.u

**Comment by guaiqueri69** [comment]
@shafayeatsumit hi, you will see result open two tabs (localhost:8888) (http://localhost:8888/api?id=1&value=100) tab 1 is change :) u.u
